language: sh
dist: focal
sudo: required

before_install:
  - sudo apt install scdoc neovim
  - git clone https://github.com/lucc/nvimpager
  - cd nvimpager
  - sudo make install
  - cd ..

script:
  - shellcheck prev
  - ./prev
