language: sh
sudo: required

before_install:
  - git clone https://git.sr.ht/~sircmpwn/scdoc/
  - cd scdoc
  - make
  - sudo make install
  - cd ..
  - git clone https://github.com/lucc/nvimpager
  - cd nvimpager
  - sudo make install
  - cd ..

script:
  - shellcheck prev
  - ./prev
