language: sh
sudo: required

before_install:
  - sudo apt install scdoc
  - sudo apt install nvimpager
  - git clone https://github.com/lucc/nvimpager
  - cd nvimpager
  - make install

script:
  - shellcheck prev
  - ./prev
