language: sh
sudo: required

before_install:
  - apt install scdoc
  - apt install nvimpager
  - git clone https://github.com/lucc/nvimpager
  - cd nvimpager
  - make install

script:
  - shellcheck prev
  - ./prev
