#!/bin/sh

LINES=100

HIGHLIGHT_THEME="${XDG_CACHE_HOME:-$HOME/.cache}/wal/pywal.theme"
HIGHLIGHT_CMD="highlight -O ansi -s $HIGHLIGHT_THEME"
PYGMENTIZE_CMD="pygmentize -f terminal"

# kitty +kitten icat --transfer-mode file --clear

case "$(file -b --mime-type "$1")" in
audio/*)
    mediainfo "$1" | $PYGMENTIZE_CMD -l make
    ;;
video/*)
    ffmpegthumbnailer -i "$1" -o /tmp/ffmpegthumbnailer.png
    chafa -c 256 /tmp/ffmpegthumbnailer.png
    mediainfo "$1" | $PYGMENTIZE_CMD -l make
    ;;
image/vnd.djvu)
    djvutxt "$1"
    ;;
application/pdf)
    pdftotext "$1" -
    ;;
image/*)
    chafa -c 256 "$1"
    # kitty +kitten icat --transfer-mode file --place 80x40@88x1 --silent "$1"
    # ueberview "$1"
    mediainfo "$1" | $PYGMENTIZE_CMD -l make
    ;;
application/zip)
    zipinfo "$1" | head -$LINES | $PYGMENTIZE_CMD -l lsl
    ;;
application/x-7z-compressed | application/x-rar)
    7z l -pa "$1" | head -$LINES | $PYGMENTIZE_CMD -l lsl
    ;;
application/zstd)
    # zstdcat "$1" | head -n30
    tar -tf "$1" | head -$LINES | $PYGMENTIZE_CMD -l lsl
    ;;
inode/symlink)
    # Shell recursion >:^)
    $0 "$(readlink -f "$1")"
    ;;
inode/chardevice)
    file -b "$1"
    ;;
application/x-iso9660-image)
    iso-info --no-header --show-rock-ridge 0 -l "$1" | nvimpager -c +"setf log"
    echo "__________________________________"
    hexdump -C "$1" | head -$LINES | $PYGMENTIZE_CMD -l hexdump
    ;;
# odt
application/vnd.oasis.* | application/vnd.openxmlformats*)
    pandoc "$1" -t markdown | $HIGHLIGHT_CMD --syntax markdown
    ;;
*/csv)
    head -$LINES "$1" | column -s, -t
    ;;
application/json)
    jq <"$1" | nvimpager -c +"setf json"
    ;;
application/*sqlite3)
    sqlite3 "$1" .dump | head -$LINES | nvimpager -c +"setf sql"
    ;;
application/gzip)
    gzip --uncompress -c "$1" | head -$LINES | $HIGHLIGHT_CMD --syntax md
    # gzip -l "$1" | $HIGHLIGHT_CMD --syntax ls
    ;;
application/octet-stream | inode/* | text/x-bytecode* | application/x-object)
    case "$(file -b "$1")" in
    "Apple binary property list")
        plistutil -i "$1" | nvimpager -c +"setf xml"
        ;;
    *)
        file -b "$1"
        echo "------------------------------------------------------------+----------------+"
        hexdump -C "$1" | head -$LINES | $PYGMENTIZE_CMD -l hexdump
        ;;
    esac
    ;;
*)
    case $1 in
    *.tar.gz | *.tgz)
        tar -ztvf "$1" | head -$LINES | $PYGMENTIZE_CMD -l lsl
        ;;
    *.tar.bz2)
        # NOTE: Get more verbose output with -v flag
        tar -jtvf "$1" | head -$LINES | $PYGMENTIZE_CMD -l lsl
        ;;
    *.tar.xz)
        tar -tvf "$1" | head -$LINES | $PYGMENTIZE_CMD -l lsl
        ;;
    *.tar)
        tar -tvf "$1" | head -$LINES | $PYGMENTIZE_CMD -l lsl
        ;;
    *.xz)
        xzcat "$1" | head -$LINES | $PYGMENTIZE_CMD -l lsl
        ;;
    *.res)
        head -$LINES "$1" | $HIGHLIGHT_CMD --syntax json
        ;;
    *)
        case "$(file -b "$1")" in
        "ASCII text, with very long lines"*)
            jq_output=$(jq <"$1" 2>/dev/null | head -$LINES)
            if [ "$jq_output" ]; then
                nvimpager -c +"setf json" <"$jq_output"
            else
                nvimpager -c "$1"
            fi
            ;;
        *)
            if command -v nvimpager >/dev/null 2>&1; then
                nvimpager -c "$1"
            else
                $PYGMENTIZE_CMD -g "$1"
                # $PYGMENTIZE_CMD -g "$1" || sudo $PYGMENTIZE_CMD -g "$1"
            fi
            ;;
        esac
        ;;
    esac
    ;;
esac
