name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run:
          - sudo add-apt-repository universe
          - sudo apt update
          - sudo apt install scdoc neovim
          - git clone https://github.com/lucc/nvimpager
          - cd nvimpager
          - sudo make install
          - cd ..
      
    - name: Install
      run: make install

    - name: Test
      run: make test
