name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch dependencies
        run: |
          sudo apt install scdoc neovim
          git clone https://github.com/lucc/nvimpager
          cd nvimpager
          sudo make install
          curl -fLo ~/.local/share/nvimpager/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      - name: Install
        run: sudo make install
      - name: Test
        run: make test
