name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch dependencies
        run: |
          sudo apt install scdoc neovim
          git clone https://github.com/lucc/nvimpager
          cd nvimpager
          sudo make install
          cd ..
      - name: Install
        run: ls && make install
      - name: Test
        run: make test
